export const styles = `
.dshPetRoot{position:absolute;z-index:4;pointer-events:auto;box-sizing:border-box;display:flex;flex-direction:column;align-items:center;gap:6px;touch-action:none;user-select:none;cursor:grab;filter:drop-shadow(0 8px 14px rgb(0 0 0 / .16))}
.dshPetRoot[data-dragging=true]{cursor:grabbing;transition:none!important}.dshPetRoot[data-motion=float]:not([data-dragging=true]){animation:dshPetFloat 3.2s ease-in-out infinite}.dshPetRoot[data-motion=bounce]:not([data-dragging=true]){animation:dshPetBounce 1.8s ease-in-out infinite}
.dshPetBubble{box-sizing:border-box;max-width:220px;min-height:28px;padding:5px 10px;border:1px solid var(--dsw-alias-border-l2,#d8dade);border-radius:8px;background:var(--dsw-alias-bg-layer-1,#fff);color:var(--dsw-alias-label-primary,#202124);font-size:12px;line-height:17px;text-align:center;box-shadow:var(--dsw-shadow-lv1,0 2px 8px rgb(0 0 0 / .08));white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dshPetStage{position:relative;width:100%;aspect-ratio:1;display:grid;place-items:center}.dshPetImage{display:block;width:100%;height:100%;object-fit:contain;pointer-events:none}.dshPetClose{position:absolute;top:2px;right:2px;width:26px;height:26px;padding:0;border:1px solid var(--dsw-alias-border-l2,#d8dade);border-radius:50%;background:var(--dsw-alias-bg-layer-1,#fff);color:var(--dsw-alias-label-secondary,#555);font:600 18px/22px system-ui;cursor:pointer;display:grid;place-items:center;box-shadow:0 2px 6px rgb(0 0 0 / .12)}.dshPetClose:hover{background:var(--dsw-alias-interactive-bg-hover,#f0f1f2);color:var(--dsw-alias-label-primary,#202124)}
.dshPetProgress{box-sizing:border-box;width:calc(100% - 12px);min-width:88px;display:flex;align-items:center;gap:7px;padding:5px 8px;border:1px solid var(--dsw-alias-border-l2,#d8dade);border-radius:8px;background:var(--dsw-alias-bg-layer-1,#fff);color:var(--dsw-alias-label-secondary,#555);font-size:11px;line-height:15px}.dshPetTrack{height:5px;min-width:34px;flex:1;border-radius:3px;background:var(--dsw-alias-interactive-bg-hover-solid,#e8eaed);overflow:hidden}.dshPetFill{height:100%;border-radius:3px;background:var(--dsw-alias-state-success-primary,#168a65);transition:width .25s ease}.dshPetCount{font-variant-numeric:tabular-nums;white-space:nowrap}
.dshPetSettings{width:100%;max-width:720px;color:var(--dsw-alias-label-primary,#202124);display:flex;flex-direction:column;gap:22px}.dshPetSettingsHeader{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding-bottom:16px;border-bottom:1px solid var(--dsw-alias-border-l2,#d8dade)}.dshPetSettingsHeader h3{margin:0 0 4px;font-size:16px;line-height:24px}.dshPetSettingsHeader p{margin:0;color:var(--dsw-alias-label-tertiary,#777);font-size:13px;line-height:20px}
.dshPetSwitch{display:inline-flex;align-items:center;gap:8px;white-space:nowrap;font-size:13px;line-height:20px;cursor:pointer}.dshPetSwitch input,.dshPetCheck input{width:16px;height:16px;accent-color:var(--dsw-alias-state-business-primary,#3f6df6)}.dshPetSettingsGrid{display:grid;grid-template-columns:minmax(0,1fr) minmax(220px,280px);gap:24px;align-items:start}.dshPetFields{display:flex;flex-direction:column;gap:16px}.dshPetField{display:flex;flex-direction:column;gap:7px}.dshPetField>span{color:var(--dsw-alias-label-secondary,#555);font-size:13px;font-weight:600;line-height:20px}
.dshPetField input[type=text],.dshPetField select{box-sizing:border-box;width:100%;height:36px;border:1px solid var(--dsw-alias-border-l2,#d8dade);border-radius:6px;background:var(--dsw-alias-bg-layer-1,#fff);color:var(--dsw-alias-label-primary,#202124);padding:0 10px;font:13px/20px system-ui;outline:none}.dshPetField input:focus-visible,.dshPetField select:focus-visible,.dshPetButton:focus-visible,.dshPetUpload:focus-within{border-color:var(--dsw-alias-state-business-primary,#3f6df6);box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-state-business-primary,#3f6df6) 18%,transparent)}
.dshPetRangeRow{display:flex;align-items:center;gap:10px}.dshPetRangeRow input{flex:1;accent-color:var(--dsw-alias-state-business-primary,#3f6df6)}.dshPetRangeRow output{width:48px;text-align:right;color:var(--dsw-alias-label-tertiary,#777);font-size:12px;font-variant-numeric:tabular-nums}.dshPetCheck{display:flex;align-items:center;gap:8px;font-size:13px;line-height:20px;cursor:pointer}.dshPetPreview{min-width:0;display:flex;flex-direction:column;align-items:center;gap:12px;padding:18px;border:1px solid var(--dsw-alias-border-l2,#d8dade);border-radius:8px;background:var(--dsw-alias-bg-layer-2,#f7f8fa)}.dshPetPreview img{width:150px;height:150px;object-fit:contain}
.dshPetActions{width:100%;display:flex;flex-wrap:wrap;justify-content:center;gap:8px}.dshPetButton,.dshPetUpload{box-sizing:border-box;min-height:32px;border:1px solid var(--dsw-alias-border-l2,#d8dade);border-radius:6px;background:var(--dsw-alias-bg-layer-1,#fff);color:var(--dsw-alias-label-primary,#202124);padding:5px 11px;font:13px/20px system-ui;cursor:pointer;text-align:center}.dshPetButton:hover,.dshPetUpload:hover{background:var(--dsw-alias-interactive-bg-hover,#f0f1f2)}.dshPetButton:disabled{cursor:not-allowed;opacity:.55}.dshPetUpload input{position:absolute;width:1px;height:1px;clip:rect(0 0 0 0);overflow:hidden}.dshPetHint{margin:0;color:var(--dsw-alias-label-tertiary,#777);font-size:12px;line-height:18px;text-align:center}.dshPetHint[data-error=true]{color:var(--dsw-alias-state-error-primary,#c73535)}
@keyframes dshPetFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-7px)}}@keyframes dshPetBounce{0%,100%{transform:translateY(0)}45%{transform:translateY(-12px)}60%{transform:translateY(-4px)}}@media (prefers-reduced-motion:reduce){.dshPetRoot{animation:none!important}.dshPetFill{transition:none}}@media (max-width:640px){.dshPetSettingsGrid{grid-template-columns:1fr}.dshPetPreview{order:-1}.dshPetSettingsHeader{align-items:center}}
`
